### ISSUE TITLE
invalid_grant error on /exchange request

### ISSUE THREAD

**Issue by ashar340** [smartcar/getting-started-node-sdk#16] opened 2021-08-11 05:42 UTC
The server throws the following upon making the request to the `/exchange` API endpoint:

```
Listening on port 8000
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

SmartcarError: invalid_grant:undefined - Unauthorized redirect_uri: http://localhost:8000/exchange
    at util.handleError (/Users/ananyasharma/dev/vroom/vroom/node_modules/smartcar/lib/util.js:105:11)
    at tryCatcher (/Users/ananyasharma/dev/vroom/vroom/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/ananyasharma/dev/vroom/vroom/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/Users/ananyasharma/dev/vroom/vroom/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ananyasharma/dev/vroom/vroom/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/ananyasharma/dev/vroom/vroom/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/ananyasharma/dev/vroom/vroom/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/ananyasharma/dev/vroom/vroom/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/ananyasharma/dev/vroom/vroom/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/ananyasharma/dev/vroom/vroom/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/ananyasharma/dev/vroom/vroom/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/ananyasharma/dev/vroom/vroom/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:464:21) {
  statusCode: 400,
  requestId: '36e8f1ab-9211-4db9-a743-180fcffd253c',
  type: 'invalid_grant',
  description: 'Unauthorized redirect_uri: http://localhost:8000/exchange'
}
```

Note that I did verify that the redirect uri, secret and clientID are correct.

**Comment by anthonywebster** [comment] 2021-10-13 04:18
Hi @ashar340, can you resolve that problem ? because I've the same problem :(

**Comment by gurpreetatwal** [comment] 2021-10-16 00:37
Closing this one as a duplicate of https://github.com/smartcar/getting-started-node-sdk/issues/16. @anthonywebster I'll be happy to help out on the linked issue :)

**Closed by gurpreetatwal** 2021-10-16 00:37 UTC

**Comment by anthonywebster** [comment] 2021-10-16 16:43
It's working. Thank you @gurpreetatwal :)

**Comment by gurpreetatwal** [comment] 2021-10-16 21:36
Anytime :) Feel free to email us at support@smartcar.com if you have any other questions or concerns!
